name: Just A Taste
favicon: null
layout_spectrum: 0.41878
typography_spectrum: 0.63198
title: Just A Taste
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b5868c'
    - '#2f2a27'
    - '#c7c7c4'
    - '#62615f'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
